[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "workout-tracking"
version = "0.2.0"
description = "A command line tool to extract workout data from markdown files."
readme = "README.md"
requires-python = ">=3.12"

[project.scripts]
workout-tracking = "workout_tracking.__main__:main"